APPLICATION_ROUTES: list[dict[str, str]] = [
    {"method": "GET", "path": "/api/application/locations"},
    {"method": "GET", "path": "/api/application/locations/{location}"},
    {"method": "POST", "path": "/api/application/locations"},
    {"method": "PATCH", "path": "/api/application/locations/{location}"},
    {"method": "DELETE", "path": "/api/application/locations/{location}"},
    {"method": "GET", "path": "/api/application/nests"},
    {"method": "GET", "path": "/api/application/nests/{nest}"},
    {"method": "GET", "path": "/api/application/nests/{nest}/eggs"},
    {"method": "GET", "path": "/api/application/nests/{nest}/eggs/{egg}"},
    {"method": "GET", "path": "/api/application/nodes"},
    {"method": "GET", "path": "/api/application/nodes/deployable"},
    {"method": "GET", "path": "/api/application/nodes/{node}"},
    {"method": "GET", "path": "/api/application/nodes/{node}/allocations"},
    {"method": "GET", "path": "/api/application/nodes/{node}/configuration"},
    {"method": "POST", "path": "/api/application/nodes"},
    {"method": "POST", "path": "/api/application/nodes/{node}/allocations"},
    {"method": "PATCH", "path": "/api/application/nodes/{node}"},
    {"method": "DELETE", "path": "/api/application/nodes/{node}"},
    {"method": "DELETE", "path": "/api/application/nodes/{node}/allocations/{allocation}"},
    {"method": "GET", "path": "/api/application/servers"},
    {"method": "GET", "path": "/api/application/servers/external/{external_id}"},
    {"method": "GET", "path": "/api/application/servers/{server}"},
    {"method": "POST", "path": "/api/application/servers"},
    {"method": "PATCH", "path": "/api/application/servers/{server}/details"},
    {"method": "PATCH", "path": "/api/application/servers/{server}/build"},
    {"method": "PATCH", "path": "/api/application/servers/{server}/startup"},
    {"method": "POST", "path": "/api/application/servers/{server}/suspend"},
    {"method": "POST", "path": "/api/application/servers/{server}/unsuspend"},
    {"method": "POST", "path": "/api/application/servers/{server}/reinstall"},
    {"method": "DELETE", "path": "/api/application/servers/{server}"},
    {"method": "GET", "path": "/api/application/servers/{server}/databases"},
    {"method": "GET", "path": "/api/application/servers/{server}/databases/{database}"},
    {"method": "POST", "path": "/api/application/servers/{server}/databases"},
    {"method": "POST", "path": "/api/application/servers/{server}/databases/{database}/reset-password"},
    {"method": "DELETE", "path": "/api/application/servers/{server}/databases/{database}"},
    {"method": "GET", "path": "/api/application/users"},
    {"method": "GET", "path": "/api/application/users/external/{external_id}"},
    {"method": "GET", "path": "/api/application/users/{user}"},
    {"method": "POST", "path": "/api/application/users"},
    {"method": "PATCH", "path": "/api/application/users/{user}"},
    {"method": "DELETE", "path": "/api/application/users/{user}"},
]

# Pterodactyl *Client* API (/api/client/...). The {server} path param is the short
# identifier (e.g. "95415e3b"), not the numeric application id. Sourced from the panel's
# routes/api-client.php route definitions.
CLIENT_ROUTES: list[dict[str, str]] = [
    # Account / meta
    {"method": "GET", "path": "/api/client"},
    {"method": "GET", "path": "/api/client/permissions"},
    {"method": "GET", "path": "/api/client/account"},
    # Server core (power / console / status are the headline endpoints)
    {"method": "GET", "path": "/api/client/servers/{server}"},
    {"method": "GET", "path": "/api/client/servers/{server}/resources"},
    {"method": "GET", "path": "/api/client/servers/{server}/websocket"},
    {"method": "POST", "path": "/api/client/servers/{server}/power"},
    {"method": "POST", "path": "/api/client/servers/{server}/command"},
    {"method": "GET", "path": "/api/client/servers/{server}/activity"},
    # Files
    {"method": "GET", "path": "/api/client/servers/{server}/files/list"},
    {"method": "GET", "path": "/api/client/servers/{server}/files/contents"},
    {"method": "GET", "path": "/api/client/servers/{server}/files/download"},
    {"method": "PUT", "path": "/api/client/servers/{server}/files/rename"},
    {"method": "POST", "path": "/api/client/servers/{server}/files/copy"},
    {"method": "POST", "path": "/api/client/servers/{server}/files/write"},
    {"method": "POST", "path": "/api/client/servers/{server}/files/compress"},
    {"method": "POST", "path": "/api/client/servers/{server}/files/decompress"},
    {"method": "POST", "path": "/api/client/servers/{server}/files/delete"},
    {"method": "POST", "path": "/api/client/servers/{server}/files/create-folder"},
    {"method": "POST", "path": "/api/client/servers/{server}/files/chmod"},
    {"method": "POST", "path": "/api/client/servers/{server}/files/pull"},
    {"method": "GET", "path": "/api/client/servers/{server}/files/upload"},
    # Databases
    {"method": "GET", "path": "/api/client/servers/{server}/databases"},
    {"method": "POST", "path": "/api/client/servers/{server}/databases"},
    {"method": "POST", "path": "/api/client/servers/{server}/databases/{database}/rotate-password"},
    {"method": "DELETE", "path": "/api/client/servers/{server}/databases/{database}"},
    # Backups
    {"method": "GET", "path": "/api/client/servers/{server}/backups"},
    {"method": "POST", "path": "/api/client/servers/{server}/backups"},
    {"method": "GET", "path": "/api/client/servers/{server}/backups/{backup}"},
    {"method": "GET", "path": "/api/client/servers/{server}/backups/{backup}/download"},
    {"method": "POST", "path": "/api/client/servers/{server}/backups/{backup}/lock"},
    {"method": "POST", "path": "/api/client/servers/{server}/backups/{backup}/restore"},
    {"method": "DELETE", "path": "/api/client/servers/{server}/backups/{backup}"},
    # Startup / settings
    {"method": "GET", "path": "/api/client/servers/{server}/startup"},
    {"method": "PUT", "path": "/api/client/servers/{server}/startup/variable"},
    {"method": "POST", "path": "/api/client/servers/{server}/settings/rename"},
    {"method": "POST", "path": "/api/client/servers/{server}/settings/reinstall"},
    {"method": "PUT", "path": "/api/client/servers/{server}/settings/docker-image"},
    # Network allocations
    {"method": "GET", "path": "/api/client/servers/{server}/network/allocations"},
    {"method": "POST", "path": "/api/client/servers/{server}/network/allocations"},
    {"method": "POST", "path": "/api/client/servers/{server}/network/allocations/{allocation}"},
    {"method": "POST", "path": "/api/client/servers/{server}/network/allocations/{allocation}/primary"},
    {"method": "DELETE", "path": "/api/client/servers/{server}/network/allocations/{allocation}"},
    # Schedules
    {"method": "GET", "path": "/api/client/servers/{server}/schedules"},
    {"method": "POST", "path": "/api/client/servers/{server}/schedules"},
    {"method": "GET", "path": "/api/client/servers/{server}/schedules/{schedule}"},
    {"method": "POST", "path": "/api/client/servers/{server}/schedules/{schedule}"},
    {"method": "POST", "path": "/api/client/servers/{server}/schedules/{schedule}/execute"},
    {"method": "DELETE", "path": "/api/client/servers/{server}/schedules/{schedule}"},
    {"method": "POST", "path": "/api/client/servers/{server}/schedules/{schedule}/tasks"},
    {"method": "POST", "path": "/api/client/servers/{server}/schedules/{schedule}/tasks/{task}"},
    {"method": "DELETE", "path": "/api/client/servers/{server}/schedules/{schedule}/tasks/{task}"},
    # Subusers
    {"method": "GET", "path": "/api/client/servers/{server}/users"},
    {"method": "POST", "path": "/api/client/servers/{server}/users"},
    {"method": "GET", "path": "/api/client/servers/{server}/users/{user}"},
    {"method": "POST", "path": "/api/client/servers/{server}/users/{user}"},
    {"method": "DELETE", "path": "/api/client/servers/{server}/users/{user}"},
]

